name: Sync platform branch with the main branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch platform branch
      run: git fetch origin platform

    - name: Sync with main
      run: |
        git checkout platform
        git pull origin main --no-rebase
        git push origin platform
